### ISSUE TITLE
How to implement stream protocol for binary data in gRPC server?

### ISSUE THREAD

**Issue by jcai** [wechaty/wechaty-puppet-hostie#106]
Recently I found some new apis about stream for binary data.Where to find some documentations to implement this in gRPC server?

**Comment by huan** [comment]
Hi @jcai , thanks for asking this question!

We have upgraded the gRPC service to use the stream for transfer files due to the problem described in https://github.com/wechaty/wechaty-puppet-hostie/issues/80, there's some related Issues & PRs linked to it and you can learn more from them for details.

For how to implement this in the gRPC server, I'd like to suggest you read [this issue](https://github.com/wechaty/grpc/issues/96) first, then read the source code in TypeScript to get to know how to implement the stream in the gRPC server.

I have refactored the related part of the codes and I hope they can be easier to be read than before, you can read them at <https://github.com/wechaty/wechaty-puppet-hostie/tree/master/src/file-box-stream>.

Please feel free to let me know if you have any questions by commenting on this issue, I hope your gRPC server will support the new stream API soon!

**Comment by jcai** [comment]
Thank you very much.Rock  supports the new stream API now !

**Comment by huan** [comment]
Awesome, congratulations!
