### ISSUE TITLE
Support rock puppet service provider.

### ISSUE THREAD

**Issue by jcai** [wechaty/wechaty-puppet-hostie#98]
Rock use same port for all user.I want to  register all tokens stored into database to `api.chatie.io`.How to use a convenient and effective method to achieve that?

**Comment by huan** [comment]
Thank you very much for asking for this new feature to our API system.

I think this request is reasonable and we should support it.

Please give me some time for thinking about how to make a great design for it, and also don't hesitate to let us know if you have any good proposals for it!

**Comment by huan** [comment]
Hi @jcai ,

After trying to think of a solution in the past three days, I think we should register our Rock token to the api.chatie.io is to follow the current standard process for now.

The current process can be described as the following two steps:

1. The `hostie server` sends a WebSocket connection to `wss://api.chatie.io/v0/websocket`, with an HTTP authorization header  `Token rock_token_here`. After the connection has been established, the `api.chatie.io` service will register your token online. (refer to the source code at <https://github.com/wechaty/wechaty/blob/7e97620e2a92841227a6ae355efa615c5af95b32/src/io.ts#L236>)
1. When a hostie discovery query has been sent to `api.chatie.io` like `https://api.chatie.io/v0/hosties/puppet_rock_token` has been visited, the `api.chatie.io` will send a JSONRPC to you via the WebSocket connection, with the method name `hostieGrpcPort`, and you need to return your service port so that it can be returned to the user. (refer to the source code at <https://github.com/wechaty/wechaty/blob/7e97620e2a92841227a6ae355efa615c5af95b32/src/io.ts#L363>)

The above two steps are the current way we are working with our service. So please feel free to read the source code from the links above, then I believe you can register multiple rock puppet token to our service with the same IP and Port without any problem.

Please feel free to let me know if you have any questions, and I hope our Rock token can be supported by our `api.chatie.io` so that the user can use the auto-discovery feature in the near future!

CC @windmemory : I said to you today that the IP is sent from the hostie server, which is not correct. After I reviewed the code, only the Port is sent from the hostie server.

**Comment by jcai** [comment]
@huan To implement the feature following your advice,Rock server will create  connection for every token.Can I use only one connection for all tokens?

**Comment by huan** [comment]
That's a great question, and it's also the reason why I think of this question for three days because I was trying to find a good idea for it but I haven't yet. Please feel free to let me know if you have any, and let's begin discussing it.

For now, I'd like to suggest that we can use multiple connections (one connection for one token) as a workaround, and we can keep improving the design of our system in the future together.

**Comment by jcai** [comment]
I think we can learn some ideas from zookeeper and etcd. It's great that I can simply register an ephemeral data to `api.chatie.io`.

**Comment by huan** [comment]
Yes, I agree. `zookeeper` and `etcd` is a very good example for us.

Do you think you send a heartbeat every a period of time for each token is acceptable? If so, how short can you prefer, for example, 15 seconds, 10 seconds, or 5 seconds?

**Comment by jcai** [comment]
I have another idea:
The hostie server can  register an` api url`  that can be used to query token a prefix string(namespace).For example：
The rock token is rock:xxxx and the padlocal token is padlocal:xxxx.The api server query endpoint  by `api  url ` registered.

**Comment by jcai** [comment]
Do you have any plan to do this issue ?

**Comment by huan** [comment]
Hi @jcai ,

I think your proposal is a good candidate for our protocol in the future, but we have to think more about it before we make any decision.

Before we can improve/redesign our protocol, I'd like to suggest that we can use multiple connections (one connection for one token) as a workaround, and we can keep improving the design of our system in the future together.

Please feel free to let me know if you have any other blocker to make your puppet service production, I hope your rock will be used by more and more Wechaty developers soon!

**Comment by jcai** [comment]
When I visit https://api.chatie.io/v0/hosties/some_token,the server don't  send jsonrpc event to my client.

log:

```
{"name":"sys","payload":"registered"}
{"name":"sys","payload":"roger"}
```

**Comment by huan** [comment]
I believe if you register the client right, it should be able to get the jsonrpc.

Please refer to https://github.com/wechaty/wechaty/blob/7e97620e2a92841227a6ae355efa615c5af95b32/src/io.ts#L363

The above code is the current running version of our system, which works as expected.

If you are experiencing any problem with getting the jsonrpc from the server, I'd like to suggest that you can test the server with our TS version of the code, and then you will be able to follow the right protocol and make your client work with our system.

Please let me know whether you can make it work after inspect the TS code, I hope you can make it work soon!

**Comment by jcai** [comment]
I think the above log evident I register my client correctly.

**Comment by jcai** [comment]
Can you help me ? My client never receive any jsonrpc event when I visit `https://api.chatie.io/v0/hosties/some_token`.

Log:

[reactor-http-nio-1   DEBUG]09:05:24 BadRegister$         sending init message:{"name":"sys","payload":"hello rock"}
[reactor-http-nio-1   DEBUG]09:05:24 BadRegister$         received message:{"name":"sys","payload":"registered"}
[reactor-http-nio-1   DEBUG]09:05:24 BadRegister$         received message:{"name":"sys","payload":"roger"}
[parallel-1           INFO ]09:05:33 BadRegister$         sending ping message
[reactor-http-nio-1   DEBUG]09:05:33 BadRegister$         received message:ping
[parallel-1           INFO ]09:05:43 BadRegister$         sending ping message
[reactor-http-nio-1   DEBUG]09:05:43 BadRegister$         received message:ping
[parallel-1           INFO ]09:05:53 BadRegister$         sending ping message
[reactor-http-nio-1   DEBUG]09:05:53 BadRegister$         received message:ping
[parallel-1           INFO ]09:06:03 BadRegister$         sending ping message
[reactor-http-nio-1   DEBUG]09:06:04 BadRegister$         received message:ping
[parallel-1           INFO ]09:06:13 BadRegister$         sending ping message
[reactor-http-nio-1   DEBUG]09:06:13 BadRegister$         received message:ping
[parallel-1           INFO ]09:06:23 BadRegister$         sending ping message
[reactor-http-nio-1   DEBUG]09:06:24 BadRegister$         received message:ping
[parallel-1           INFO ]09:06:33 BadRegister$         sending ping message
[reactor-http-nio-1   DEBUG]09:06:33 BadRegister$         received message:ping
[parallel-1           INFO ]09:06:43 BadRegister$         sending ping message
[reactor-http-nio-1   DEBUG]09:06:44 BadRegister$         received message:ping
[parallel-1           INFO ]09:06:53 BadRegister$         sending ping message
[reactor-http-nio-1   DEBUG]09:06:54 BadRegister$         received message:ping
[parallel-1           INFO ]09:07:03 BadRegister$         sending ping message
[reactor-http-nio-1   DEBUG]09:07:04 BadRegister$         received message:ping
[parallel-1           INFO ]09:07:13 BadRegister$         sending ping message
[reactor-http-nio-1   DEBUG]09:07:13 BadRegister$         received message:ping
[parallel-1           INFO ]09:07:23 BadRegister$         sending ping message
[reactor-http-nio-1   DEBUG]09:07:23 BadRegister$         received message:ping
[parallel-1           INFO ]09:07:33 BadRegister$         sending ping message
[reactor-http-nio-1   DEBUG]09:07:33 BadRegister$         received message:ping

**Comment by huan** [comment]
Could you please post your code of the websocket connecting to the server so that I can read it and try to figure out the problem from it for you?

**Comment by huan** [comment]
If you are experiencing an unstable connection to our api.chatie.io, that's because you have issues between your server and the cloudflare (the cdn service we are using).

You can use https://chatieio.herokuapp.com as an alternative endpoint, which is our api service itself.

Our client will use it as an fallback as well, see: 

https://github.com/wechaty/wechaty-puppet-hostie/blob/d619d08ccb7bdc6ad36cd2dbafd22033fdee8659/src/client/puppet-hostie.ts#L169

**Comment by jcai** [comment]
```scala
def main(args: Array[String]): Unit = {
    val uri= new URI("wss://api.chatie.io/v0/websocket")
    val client = new ReactorNettyWebSocketClient
    val headers = new HttpHeaders()
    headers.add("Authorization","Token some_token")
    client.execute(uri,headers,new WebSocketHandler {
      override def handle(session: WebSocketSession): Mono[Void] = {
        SFlux.interval(Duration.apply("10s")).flatMap{_=>
          logger.info("sending ping message")
          val pingData = session.pingMessage(df=>{
            df.wrap("ping".getBytes(StandardCharsets.UTF_8))
          })
          session.send(Mono.just(pingData))
        }.subscribe()

        val helloPayload = new IoEvent
        helloPayload.name="sys"
        helloPayload.payload="hello rock"
        val initPayload = HttpClientHelper.OBJECT_MAPPER.writeValueAsString(helloPayload)
        logger.debug("sending init message:{}",initPayload)
        session.send(Mono.just(session.textMessage(initPayload))).thenMany(
          session.receive().asScala.flatMap{message=>
            logger.debug("received message:{}",message.getPayloadAsText)
            Mono.just("OK")//.`then`()
          }).count().`then`()
      }
    }).subscribe()
```

**Comment by huan** [comment]
Thank you very much for sharing your minimum code!

According to your code, it seems that you have missed the `protocol` part in your web socket connection.

Please refer to 

https://github.com/wechaty/wechaty/blob/30c446b2b78c92166a1d613952e77d3e3fdbbe1f/src/io.ts#L236

And set the protocol correctly by aligning to the TS code.

Please let me know if you have any problem after your set it right, I hope it will be able to work soon!

**Comment by jcai** [comment]
Thank you very much.It works well now!!!

**Comment by huan** [comment]
You are welcome, cheers! 👍
